version: "2.18.1"
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    command: gunicorn club_directory.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - media_volume:/usr/src/app/media
    depends_on:
      - db
    env_file:
      - ./.env.prod
  db:
    image: postgres:15.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
     - ./.env.prod.db

volumes:
  postgres_data:
  media_volume: