version: "2.18.1"
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn club_directory.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    volumes:
      - media_volume:/usr/src/app/media
  db:
    image: postgres:15.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  media_volume: