# Generated by Django 4.2.1 on 2023-06-06 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_rename_is_admin_user_isadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagesPosted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('announcement', models.TextField(blank=True)),
                ('interestCount', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clubsCreated', to=settings.AUTH_USER_MODEL)),
                ('editors', models.ManyToManyField(related_name='clubsEditing', to=settings.AUTH_USER_MODEL)),
                ('messages', models.ManyToManyField(related_name='clubs', to='clubs.message')),
            ],
        ),
    ]
