# Generated by Django 4.2.1 on 2023-06-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_message_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
