# Generated by Django 4.2.1 on 2023-06-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_isapproved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='clubs', to='clubs.message'),
        ),
    ]
